// src/app/[lang]/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { type SupportedLanguages } from "@/i18n/types";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ 
    lang: SupportedLanguages 
  }>;
}

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "af" }];
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const { lang } = await params;
  
  return (
    <html lang={lang}>
      <body className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}